blank_issues_enabled: false
contact_links:
  - name: Azion Support
    url: https://tickets.azion.com/en/support/login/new
    about: Contact the Support team if you're having trouble with an Azion product.
