name: Request content addition
description: Suggest the addition of missing content about undocumented products or features.
title: "[ADD] <title>"
body:
  - type: markdown
    attributes:
      value: |
        :wave: Hey, we appreciate your contribution! Please fill in the fields below to open a new issue.
        ➕ Use this type of issue to propose enhancements to the existing Azion product documentation and help us keep it more complete.

  - type: checkboxes
    id: existing
    attributes:
      label: Is there an issue open for this?
      description: Please check the [existing issues](https://github.com/aziontech/docs/issues) to see if a similar issue already exists.
      options:
      - label: I've searched the existing issues.
        required: true

  - type: checkboxes
    id: contributing
    attributes:
      label: Have you read our contributing guidelines?
      description: Please read our **Contributing guidelines** before making a contribution.
      options:
      - label: I've read the guidelines.
        required: true
        
  - type: input
    attributes:
      label: Subject matter
      description: What needs to be documented?
    validations:
      required: true

  - type: input
    attributes:
      label: Suggested URL for the content
      description: |
        If the content to be added should be included in or linked to an existing URL, you may link it here. 
        You may also suggest a likely URL for the content.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Description
      description: |
        Describe what's missing on the Azion Docs portal.
        You can attach screenshots or links if needed.
    validations:
      required: true
