name: Report an error
description: Report an issue with the Azion Docs portal.
title: "[FIX] <title>"
body:
  - type: markdown
    attributes:
      value: |
        :wave: Hey, we appreciate your contribution! Please fill in the fields below to open a new issue.
        ❌ Error issues are reserved for potential issues, faults, or anomalies with the Azion Docs portal that mislead or hinder the overall usability of Azion products.

  - type: checkboxes
    id: existing
    attributes:
      label: Is there an issue open for this?
      description: Please check the [existing issues](https://github.com/aziontech/docs/issues) to see if a similar issue already exists.
      options:
      - label: I've searched the existing issues.
        required: true

  - type: checkboxes
    id: contributing
    attributes:
      label: Have you read our contributing guidelines?
      description: Please read our **Contributing guidelines** before making a contribution.
      options:
      - label: I've read the guidelines.
        required: true

  - type: textarea
    attributes:
      label: Documentation URLs
      description: Please, provide links to the existing [Azion Docs](https://docs.azion.com) page or pages that contain the error.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: |
        Describe the error you found in the documentation portal and how it should be fixed.
        You can attach screenshots or links for reference.
    validations:
      required: true
