name: Ask a question
description: Contact us if you have any questions about our content.
title: "[QUESTION] <title>"
body:
  - type: markdown
    attributes:
      value: |
        :wave: Hey, we appreciate your contribution!
  - type: checkboxes
    id: existing
    attributes:
      label: Is there an existing issue for this?
      description: Please check the [existing issues](https://github.com/aziontech/docs/issues) to see if a similar issue already exists.
      options:
      - label: I have searched the existing issues.
        required: true
  - type: checkboxes
    id: contributing
    attributes:
      label: Have you read our contributing guidelines?
      description: Please read our **Contributing guidelines** before making a contribution.
      options:
      - label: I have read the guidelines.
        required: true
  - type: textarea
    attributes:
      label: Question
      description: Describe what questions you have. We'll make sure to get back to you as soon as possible.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Links or references
      description: |
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
