name: Request content addition
description: Suggest the addition of missing content about undocumented products or features.
title: "[ADD] <title>"
body:
  - type: markdown
    attributes:
      value: |
        :wave: Hey, we appreciate your contribution!
        
  - type: checkboxes
    id: existing
    attributes:
      label: Is there an existing issue for this?
      description: Please check the [existing issues](https://github.com/aziontech/docs/issues) to see if a similar issue already exists.
      options:
      - label: I have searched the existing issues.
        required: true

  - type: checkboxes
    id: contributing
    attributes:
      label: Have you read our contributing guidelines?
      description: Please read our **Contributing guidelines** before making a contribution.
      options:
      - label: I have read the guidelines.
        required: true

  - type: input
  attributes:
    label: Subject matter
    description: |
      What needs to be documented?
  validations:
    required: true

  - type: textarea
    attributes:
      label: Addition details
      description: |
        Give as much detail as you can to help us understand what is missing from the docs.
        Can't find any content about one of our products? Is it available in the Azion platform?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Links or references
      description: |
        Add any other context or screenshots about the feature here.
    validations:
      required: false

