name: Ask a question
description: Contact us if you have any questions about our content.
title: "[QUESTION] <title>"
body:
  - type: markdown
    attributes:
      value: |
        :wave: Hey, we appreciate your contribution! Please fill in the fields below to open a new issue.
        ❓ This type of issue is reserved for questions about the content in the Azion Docs portal.

  - type: checkboxes
    id: existing
    attributes:
      label: Is there an issue open for this?
      description: Please check the [existing issues](https://github.com/aziontech/docs/issues) to see if a similar issue already exists.
      options:
      - label: I've searched the existing issues.
        required: true

  - type: checkboxes
    id: contributing
    attributes:
      label: Have you read our contributing guidelines?
      description: Please read our **Contributing guidelines** before making a contribution.
      options:
      - label: I've read the guidelines.
        required: true

  - type: textarea
    attributes:
      label: Description
      description: |
        Describe your questions about the current documentation.
        You can attach screenshots or links for reference.
    validations:
      required: true
