name: Update content
description: Make a suggestion to improve the Azion Docs portal.
title: "[UPKEEP] <title>"
body:
  - type: markdown
    attributes:
      value: |
        :wave: Hey, we appreciate your contribution!

  - type: checkboxes
    id: existing
    attributes:
      label: Is there an issue open for this?
      description: Please check the [existing issues](https://github.com/aziontech/docs/issues) to see if a similar issue already exists.
      options:
      - label: I have searched the existing issues.
        required: true

  - type: checkboxes
    id: contributing
    attributes:
      label: Have you read our contributing guidelines?
      description: Please read our **Contributing guidelines** before making a contribution.
      options:
      - label: I have read the guidelines.
        required: true

  - type: textarea
    attributes:
      label: Documentation URLs
      description: Please provide links to one of our existing [Azion Docs](https://docs.azion.com) pages.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: |
        Describe what should be updated on the Azion Docs portal.
        You can attach screenshots or links for reference.
    validations:
      required: true
