name: Update content
description: Make a suggestion to improve the Azion Docs portal.
title: "[UPKEEP] <title>"
  - type: markdown
    attributes:
      value: |
        :wave: Hey, we appreciate your contribution!
  - type: checkboxes
    id: existing
    attributes:
      label: Is there an existing issue for this?
      description: Please check the [existing issues](https://github.com/aziontech/docs/issues) to see if a similar issue already exists.
      options:
      - label: I have searched the existing issues.
        required: true
  - type: checkboxes
    id: contributing
    attributes:
      label: Have you read our contributing guidelines?
      description: Please read our [Contributing guidelines](link) before making a contribution.
      options:
      - label: I have read the guidelines.
        required: true
  - type: input
    attributes:
      label: Documentation URL
      description: Please provide links to one of our existing [Azion Docs](https://docs.azion.com) pages.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Describe what should be changed in the content.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Links or references
      description: |
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true
