---
new_page_extension: md
auto_deploy: false
sections:
- type: directory
  path: ''
  label: Productos
  create: all
  match: "**/*"
  templates:
  - products-documentation
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
