---
label: Products documentation
hide_body: false
fields:
- type: text
  name: layout
  label: layout
  config:
    required: true
  default: page-documentation-md
- type: text
  name: title
  label: title
  config:
    required: true
- type: text
  name: description
  label: description
  config:
    required: true
- type: text
  name: meta_tags
  label: meta_tags
  config:
    required: true
- type: text
  name: namespace
  label: namespace
  config:
    required: true
- type: text
  name: permalink
  label: permalink
- type: text
  name: permalink_es
  label: permalink_es
  config:
    required: true
- type: text
  name: permalink_pt-br
  label: permalink_pt-br
