import fs from 'node:fs';
import path from 'node:path';

import { LANGS, type Lang } from '../../src/nav/schema';
import { DOCS_BASE, targetPermalink, walkTree, withSlashes } from '../../src/nav/resolve';
import { loadNav, REPO_ROOT, type CorpusPage } from './lib/load';
import { removeField, setField } from './lib/frontmatter';

const SITE = 'https://www.azion.com';
const OUT_DIR = path.join(REPO_ROOT, 'redirects');
const apply = process.argv.includes('--apply');

const { data, redirects, corpus, issues } = loadNav();
if (issues.length) {
	console.error('nav data does not load cleanly; run lint:navcheck first');
	for (const issue of issues) console.error(`  ${issue}`);
	process.exit(1);
}

const byNamespace = new Map<string, Partial<Record<Lang, CorpusPage>>>();
for (const page of corpus) {
	const entry = byNamespace.get(page.namespace) ?? {};
	entry[page.lang] = page;
	byNamespace.set(page.namespace, entry);
}

interface Move {
	namespace: string;
	lang: Lang;
	treeId: string;
	title: string;
	from: string;
	to: string;
}

const moves: Move[] = [];
/** namespace -> lang -> new permalink, so a discarded page can point at where its replacement lands. */
const landing = new Map<string, Partial<Record<Lang, string>>>();

for (const lang of LANGS) {
	for (const tree of data.trees.values()) {
		for (const entry of walkTree(tree, lang)) {
			const { node } = entry;
			if (!node.page || node.linkOnly || node.placeholder) continue;
			const page = byNamespace.get(node.page)?.[lang];
			if (!page) continue;
			const to = targetPermalink(data, entry, lang);
			if (!to) continue;
			const spot = landing.get(node.page) ?? {};
			spot[lang] = to;
			landing.set(node.page, spot);
			if (withSlashes(page.permalink) === withSlashes(to)) continue;
			moves.push({ namespace: node.page, lang, treeId: tree.id, title: page.title, from: page.permalink, to });
		}
	}
}

function discardTarget(namespace: string, lang: Lang): string | undefined {
	const target = redirects[namespace];
	if (!target) return undefined;
	if (target.page) return landing.get(target.page)?.[lang] ?? byNamespace.get(target.page)?.[lang]?.permalink;
	if (target.tree) {
		const tree = data.trees.get(target.tree);
		if (!tree) return undefined;
		if (tree.root) return landing.get(tree.root)?.[lang];
		return `/${DOCS_BASE[lang]}/${(lang === 'en' ? tree.path.en : tree.path['pt-br'] ?? tree.path.en)}/`;
	}
	if (target.path) return target.path.replace('/documentation/', `/${DOCS_BASE[lang]}/`);
	return undefined;
}

interface Removal {
	namespace: string;
	lang: Lang;
	title: string;
	from: string;
	to: string;
	reason: string;
}

const removals: Removal[] = [];
for (const namespace of Object.keys(redirects)) {
	for (const lang of LANGS) {
		const page = byNamespace.get(namespace)?.[lang];
		if (!page) continue;
		const to = discardTarget(namespace, lang);
		if (!to) {
			console.error(`no replacement URL for discarded page "${namespace}" (${lang})`);
			continue;
		}
		removals.push({ namespace, lang, title: page.title, from: page.permalink, to, reason: redirects[namespace].reason });
	}
}

const url = (lang: Lang, permalink: string) => `${SITE}/${lang}${withSlashes(permalink)}`;

fs.mkdirSync(OUT_DIR, { recursive: true });

for (const lang of LANGS) {
	const rows = [
		...moves.filter((m) => m.lang === lang).map((m) => ({ from: url(lang, m.from), moved: url(lang, m.to) })),
		...removals.filter((r) => r.lang === lang).map((r) => ({ from: url(lang, r.from), moved: url(lang, r.to) })),
	].filter((row) => row.from !== row.moved);
	fs.writeFileSync(path.join(OUT_DIR, `url-map.${lang}.json`), JSON.stringify(rows, null, 1) + '\n');
}

const treeOrder = [...data.trees.keys()];
const lines: string[] = [];
lines.push('# URL map');
lines.push('');
lines.push('Every documentation URL this navigation rework moves or retires, old on the left, new on the right.');
lines.push('Generated by `scripts/nav/migrate-permalinks.ts`; the machine-readable twin is `url-map.en.json` and `url-map.pt-br.json`.');
lines.push('');
lines.push(`- Pages moved: ${moves.filter((m) => m.lang === 'en').length} English, ${moves.filter((m) => m.lang === 'pt-br').length} Portuguese`);
lines.push(`- Pages retired: ${removals.filter((r) => r.lang === 'en').length} English, ${removals.filter((r) => r.lang === 'pt-br').length} Portuguese`);
lines.push('');

for (const treeId of treeOrder) {
	const tree = data.trees.get(treeId)!;
	const mine = moves.filter((m) => m.treeId === treeId);
	if (!mine.length) continue;
	lines.push(`## ${tree.title.en}`);
	lines.push('');
	for (const lang of LANGS) {
		const rows = mine.filter((m) => m.lang === lang);
		if (!rows.length) continue;
		lines.push(`### ${lang}`);
		lines.push('');
		lines.push('| Page | Old URL | New URL |');
		lines.push('| --- | --- | --- |');
		for (const row of rows.sort((a, b) => a.to.localeCompare(b.to))) {
			lines.push(`| ${row.title.replace(/\|/g, '\\|')} | \`${row.from}\` | \`${row.to}\` |`);
		}
		lines.push('');
	}
}

lines.push('## Retired pages');
lines.push('');
lines.push('These leave the navigation. The files stay in the repository; the URL points at the replacement.');
lines.push('');
for (const lang of LANGS) {
	const rows = removals.filter((r) => r.lang === lang);
	if (!rows.length) continue;
	lines.push(`### ${lang}`);
	lines.push('');
	lines.push('| Page | Old URL | Replaced by | Why |');
	lines.push('| --- | --- | --- | --- |');
	for (const row of rows.sort((a, b) => a.from.localeCompare(b.from))) {
		lines.push(`| ${row.title.replace(/\|/g, '\\|')} | \`${row.from}\` | \`${row.to}\` | ${row.reason} |`);
	}
	lines.push('');
}

fs.writeFileSync(path.join(OUT_DIR, 'url-map.md'), lines.join('\n'));

if (apply) {
	let touched = 0;
	for (const move of moves) {
		const page = byNamespace.get(move.namespace)?.[move.lang];
		if (!page) continue;
		const file = path.join(REPO_ROOT, 'src/content/docs', page.file);
		const before = fs.readFileSync(file, 'utf8');
		const after = removeField(setField(before, 'permalink', move.to), 'menu_namespace');
		if (after !== before) {
			fs.writeFileSync(file, after);
			touched += 1;
		}
	}
	for (const page of corpus) {
		if (!page.menuNamespace) continue;
		const file = path.join(REPO_ROOT, 'src/content/docs', page.file);
		const before = fs.readFileSync(file, 'utf8');
		const after = removeField(before, 'menu_namespace');
		if (after !== before) {
			fs.writeFileSync(file, after);
			touched += 1;
		}
	}
	console.log(`applied: ${touched} files rewritten`);
} else {
	console.log('dry run: no content files were touched (pass --apply to rewrite frontmatter)');
}

console.log(`moved   ${moves.length} page/language pairs`);
console.log(`retired ${removals.length} page/language pairs`);
console.log(`wrote   redirects/url-map.md, url-map.en.json, url-map.pt-br.json`);
