name: Documentation development pipeline

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Development publising
    runs-on: self-hosted
    container:
      image: ubuntu:latest

    steps:
      - name: CHECKOUT project
        uses: actions/checkout@v3
        with:
          repository: aziontech/docs
          ref: dev
          path: '.'
          clean: true
          fetch-depth: '0'
          lfs: 'false'

      - name: SETTING Node and Github Packages
        uses: actions/setup-node@v3
        with:
          node-version: 20.6.1

      - name: INSTALLING DEPENDENCIES
        run: npm install

    #   - name: CHECKER
    #     run: npm run check

      - name: BUILD
        run: npm run build

      - name: PREPARE TO DEPLOYMENT
        run: rm -rf .eslintignore .eslintrc.js .prettierignore .prettierrc .nvmrc .npmrc pnpm-lock.yaml .astro .github node_modules src .editorconfig .gitignore astro.config.ts LICENSE package-lock.json package.json README.md tsconfig.json public plugins scripts integrations doc-bkp cmd.txt cloudcannon.config.yml _cloudcannon

      - name: PREPARE DIST FOLDER
        run: mv dist/* ./ && rm -rf dist

      - name: DEPLOYMENT
        uses: patrickwyler/gcs-bucket-sync-action@1.3
        with:
          secrets: ${{ secrets.GCP_EXP_ENG }}
          bucket: azdocs-dev
