name: Documentation development pipeline
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    name: Development publising
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT project
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          repository: aziontech/docs
          ref: dev
          path: '.'
          clean: true
          fetch-depth: '0'
          lfs: 'false'
      - name: SETTING pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
      - name: SETTING Node and Github Packages
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22.23.2
          cache: 'pnpm'
      - name: INSTALLING DEPENDENCIES
        run: |
          pnpm install --frozen-lockfile
      - name: BUILD
        run: |
          export NODE_OPTIONS="--max-old-space-size=8120"
          export PUBLIC_GITHUB_TOKEN="${{ secrets.GH_PACKAGES_SECRET }}"
          pnpm run build:dev
      - name: 'AUTH Google Cloud'
        uses: google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed # v2.1.13
        with:
          credentials_json: ${{ secrets.GCP_EXP_ENG }}
      - uses: google-github-actions/setup-gcloud@e427ad8a34f8676edf47cf7d7925499adf3eb74f # v2.2.1
        with:
          version: '>= 363.0.0'
      - name: PUBLISHING
        run: |
          gsutil -m rsync -r -d dist gs://azdocs-dev
      - name: UPDATING Google Cloud Storage files Cache-Control header
        run: |
          gcloud storage objects update -r gs://azdocs-dev --cache-control="public, max-age=120"
      # - name: PURGE Edge Cache
      #   run: |
      #     pnpm add axios
      #     node ./cicd/cdn-purge.js basic_token=${{ secrets.MKT_BASE64_TOKEN }}
