name: Documentation development pipeline
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    name: Development publising
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT project
        uses: actions/checkout@v4
        with:
          repository: aziontech/docs
          ref: dev
          path: '.'
          clean: true
          fetch-depth: '0'
          lfs: 'false'
      - name: SETTING Node and Github Packages
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.1
      - name: INSTALLING DEPENDENCIES
        run: |
          npm install
      - name: BUILD
        run: |
          export NODE_OPTIONS="--max-old-space-size=8120"
          export PUBLIC_GITHUB_TOKEN="${{ secrets.GH_PACKAGES_SECRET }}"
          npm run build-development
      - name: PREPARE TO DEPLOYMENT
        run: |
          rm -rf .eslintignore .eslintrc.js .prettierignore .prettierrc .nvmrc .npmrc pnpm-lock.yaml .astro .github node_modules src .editorconfig .gitignore astro.config.ts LICENSE package-lock.json package.json README.md tsconfig.json public plugins cicd .git CODE_OF_CONDUCT.md helpcenter-cleaner.js postcss.config.js
      - name: PREPARE DIST FOLDER
        run: |
          mv dist/* ./
          rm -rf dist
      - name: PUBLISING
        uses: patrickwyler/gcs-bucket-sync-action@1.3
        with:
          secrets: ${{ secrets.GCP_EXP_ENG }}
          bucket: azdocs-dev
