name: Internal links

on:
  pull_request:
    branches:
      - main
      - release/new-azion-docs
    types: [opened, synchronize, reopened]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  internal-links:
    name: Internal links
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup

      - name: Build the site
        run: pnpm build:local
        env:
          NODE_OPTIONS: --max-old-space-size=8120
          SKIP_OG: 'true'
          
      - name: Link check (ratchet)
        run: pnpm ci:ratchet linkcheck
